# Site settings
title: Prog Metal
email: oyshole@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Programming Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://oyshole.github.io" # the base hostname & protocol for your site
twitter_username: oyshole
github_username: oyshole

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: rouge
# rouge_options: ["linenos=table"]

#redcarpet:
#  extensions: ["line_numbers", "tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
